import * as Blockly from 'blockly'

export function registerOpenApiMvpBlocks() {
  if (Blockly.Blocks['openapi_root']) return

  Blockly.defineBlocksWithJsonArray([
    {
      type: 'openapi_root',
      message0:
        'OpenAPI %1 titre %2 version %3 %4 schémas réutilisables %5 schémas de sécurité %6 sécurité globale %7 paths %8',
      args0: [
        {
          type: 'field_dropdown',
          name: 'OPENAPI_VERSION',
          options: [
            ['3.0.3', '3.0.3'],
            ['3.1.0', '3.1.0'],
          ],
        },
        { type: 'field_input', name: 'TITLE', text: 'Mon API' },
        { type: 'field_input', name: 'API_VERSION', text: '1.0.0' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'SCHEMA_DEFS', check: 'SCHEMA_DEF' },
        { type: 'input_statement', name: 'SECURITY_SCHEMES', check: 'SECURITY_SCHEME_DEF' },
        { type: 'input_statement', name: 'GLOBAL_SECURITY', check: 'SECURITY_REQUIREMENT' },
        { type: 'input_statement', name: 'PATHS', check: 'PATH' },
      ],
      colour: 285,
      tooltip: 'Point d’entrée du contrat OpenAPI (MVP).',
      helpUrl: '',
      hat: 'cap',
    },
    {
      type: 'openapi_path',
      message0: 'path %1 %2 methods %3',
      args0: [
        { type: 'field_input', name: 'PATH', text: '/hello' },
        { type: 'input_dummy' },
        { type: 'input_statement', name: 'METHODS', check: 'METHOD' },
      ],
      previousStatement: 'PATH',
      nextStatement: 'PATH',
      colour: 210,
      tooltip: 'Un PathItem OpenAPI (ex: /users/{id}).',
      helpUrl: '',
    },
    {
      type: 'openapi_method',
      message0: 'méthode %1 résumé %2 sécurité %3 %4 responses %5',
      args0: [
        {
          type: 'field_dropdown',
          name: 'VERB',
          options: [
            ['GET', 'get'],
            ['POST', 'post'],
            ['PUT', 'put'],
            ['PATCH', 'patch'],
            ['DELETE', 'delete'],
          ],
        },
        { type: 'field_input', name: 'SUMMARY', text: 'Décrit ce que fait l’endpoint' },
        {
          type: 'field_dropdown',
          name: 'SECURITY_MODE',
          options: [
            ['hérite (global)', 'inherit'],
            ['override (spécifique)', 'override'],
            ['aucune (public)', 'none'],
          ],
        },
        { type: 'input_statement', name: 'SECURITY', check: 'SECURITY_REQUIREMENT' },
        { type: 'input_statement', name: 'RESPONSES', check: 'RESPONSE' },
      ],
      previousStatement: 'METHOD',
      nextStatement: 'METHOD',
      colour: 160,
      tooltip: 'Une Operation (verbe HTTP) pour un path.',
      helpUrl: '',
    },
    {
      type: 'openapi_response',
      message0: 'response %1 description %2 %3 schema %4',
      args0: [
        { type: 'field_input', name: 'STATUS', text: '200' },
        { type: 'field_input', name: 'DESCRIPTION', text: 'OK' },
        { type: 'input_dummy' },
        { type: 'input_value', name: 'SCHEMA', check: 'SCHEMA' },
      ],
      previousStatement: 'RESPONSE',
      nextStatement: 'RESPONSE',
      colour: 65,
      tooltip: 'Une réponse HTTP (code + description + schema optionnel).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_primitive',
      message0: 'primitive type %1 format %2',
      args0: [
        {
          type: 'field_dropdown',
          name: 'TYPE',
          options: [
            ['string', 'string'],
            ['number', 'number'],
            ['integer', 'integer'],
            ['boolean', 'boolean'],
          ],
        },
        { type: 'field_input', name: 'FORMAT', text: '' },
      ],
      message1: 'description %1 example (JSON ou texte) %2',
      args1: [
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
        { type: 'field_input', name: 'EXAMPLE', text: '' },
      ],
      output: 'SCHEMA',
      colour: 20,
      tooltip: 'Type JSON Schema simple + description / exemple optionnels.',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_ref',
      message0: '$ref schema %1',
      args0: [{ type: 'field_input', name: 'REF_NAME', text: 'MonModele' }],
      message1: 'description %1 example (JSON ou texte) %2',
      args1: [
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
        { type: 'field_input', name: 'EXAMPLE', text: '' },
      ],
      output: 'SCHEMA',
      colour: 290,
      tooltip: '#/components/schemas/<nom>. Avec description/exemple : enveloppé en allOf (compatible OAS 3.0).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_object',
      message0: 'object description %1',
      args0: [{ type: 'field_input', name: 'DESCRIPTION', text: '' }],
      message1: 'properties %1',
      args1: [{ type: 'input_statement', name: 'PROPERTIES', check: 'PROPERTY' }],
      output: 'SCHEMA',
      colour: 25,
      tooltip: 'Objet avec propriétés (chaîne de blocs « propriété »).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_property',
      message0: 'propriété %1 requis %2 %3 schema %4',
      args0: [
        { type: 'field_input', name: 'NAME', text: 'id' },
        { type: 'field_checkbox', name: 'REQUIRED', checked: false },
        { type: 'input_dummy' },
        { type: 'input_value', name: 'VALUE', check: 'SCHEMA' },
      ],
      message1: 'description %1 example (JSON ou texte) %2',
      args1: [
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
        { type: 'field_input', name: 'EXAMPLE', text: '' },
      ],
      previousStatement: 'PROPERTY',
      nextStatement: 'PROPERTY',
      colour: 30,
      tooltip: 'Une propriété d’objet (nom, schéma, requis, description, exemple).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_array',
      message0: 'array description %1 %2 items %3',
      args0: [
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
        { type: 'input_dummy' },
        { type: 'input_value', name: 'ITEMS', check: 'SCHEMA' },
      ],
      output: 'SCHEMA',
      colour: 15,
      tooltip: 'Tableau : schéma des éléments via le bloc branché sur « items ».',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_allOf',
      message0: 'allOf %1 %2 %3',
      args0: [
        { type: 'input_value', name: 'A', check: 'SCHEMA' },
        { type: 'input_value', name: 'B', check: 'SCHEMA' },
        { type: 'input_value', name: 'C', check: 'SCHEMA' },
      ],
      output: 'SCHEMA',
      colour: 260,
      tooltip: 'Combine plusieurs schémas (jusqu’à 3 ; imbrique ce bloc pour en ajouter).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_oneOf',
      message0: 'oneOf %1 %2 %3',
      args0: [
        { type: 'input_value', name: 'A', check: 'SCHEMA' },
        { type: 'input_value', name: 'B', check: 'SCHEMA' },
        { type: 'input_value', name: 'C', check: 'SCHEMA' },
      ],
      output: 'SCHEMA',
      colour: 265,
      tooltip: 'Exactement une des alternatives (jusqu’à 3).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_anyOf',
      message0: 'anyOf %1 %2 %3',
      args0: [
        { type: 'input_value', name: 'A', check: 'SCHEMA' },
        { type: 'input_value', name: 'B', check: 'SCHEMA' },
        { type: 'input_value', name: 'C', check: 'SCHEMA' },
      ],
      output: 'SCHEMA',
      colour: 270,
      tooltip: 'Au moins une des alternatives (jusqu’à 3).',
      helpUrl: '',
    },
    {
      type: 'openapi_schema_def',
      message0: 'schema nom %1 définition %2',
      args0: [
        { type: 'field_input', name: 'SCHEMA_NAME', text: 'MonModele' },
        { type: 'input_value', name: 'SCHEMA', check: 'SCHEMA' },
      ],
      previousStatement: 'SCHEMA_DEF',
      nextStatement: 'SCHEMA_DEF',
      colour: 45,
      tooltip: 'Déclare un schéma réutilisable sous components.schemas.',
      helpUrl: '',
    },
    {
      type: 'openapi_security_scheme_jwt',
      message0: 'security scheme JWT id %1 description %2 bearerFormat %3',
      args0: [
        { type: 'field_input', name: 'SCHEME_ID', text: 'jwtAuth' },
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
        { type: 'field_input', name: 'BEARER_FORMAT', text: 'JWT' },
      ],
      previousStatement: 'SECURITY_SCHEME_DEF',
      nextStatement: 'SECURITY_SCHEME_DEF',
      colour: 110,
      tooltip: 'Déclare un securityScheme HTTP bearer (JWT).',
      helpUrl: '',
    },
    {
      type: 'openapi_security_scheme_header',
      message0: 'security scheme Header id %1 header %2 description %3',
      args0: [
        { type: 'field_input', name: 'SCHEME_ID', text: 'apiKeyAuth' },
        { type: 'field_input', name: 'HEADER_NAME', text: 'X-API-KEY' },
        { type: 'field_input', name: 'DESCRIPTION', text: '' },
      ],
      previousStatement: 'SECURITY_SCHEME_DEF',
      nextStatement: 'SECURITY_SCHEME_DEF',
      colour: 110,
      tooltip: 'Déclare un securityScheme apiKey dans le header (custom).',
      helpUrl: '',
    },
    {
      type: 'openapi_security_requirement',
      message0: 'require %1',
      args0: [{ type: 'field_input', name: 'SCHEME_ID', text: 'jwtAuth' }],
      previousStatement: 'SECURITY_REQUIREMENT',
      nextStatement: 'SECURITY_REQUIREMENT',
      colour: 120,
      tooltip:
        'Ajoute une exigence de sécurité (ex: jwtAuth). Chaîne de blocs = plusieurs exigences (OR) comme OpenAPI security[].',
      helpUrl: '',
    },
  ])
}

